//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eLTMS.Web.DbConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Appointment()
        {
            this.SampleGettings = new HashSet<SampleGetting>();
        }
    
        public string AppointmentCode { get; set; }
        public Nullable<int> PatientID { get; set; }
        public Nullable<int> DoctorID { get; set; }
        public Nullable<bool> IsEmergency { get; set; }
        public string TestPurpose { get; set; }
        public Nullable<System.DateTime> EnterTime { get; set; }
        public Nullable<System.DateTime> ReturnTime { get; set; }
        public string Conclusion { get; set; }
        public Nullable<bool> ResultApproved { get; set; }
        public string Status { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public int AppointmentID { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Patient Patient { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SampleGetting> SampleGettings { get; set; }
    }
}
