//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eLTMS.Web.DbConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportPaperDetail
    {
        public int ImportPaperDetailId { get; set; }
        public Nullable<int> ImportPaperId { get; set; }
        public Nullable<int> SuppliesId { get; set; }
        public string Unit { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Note { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual ImportPaper ImportPaper { get; set; }
        public virtual Supply Supply { get; set; }
    }
}
