//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eLTMS.Web.DbConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportPaper
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ImportPaper()
        {
            this.ImportPaperDetails = new HashSet<ImportPaperDetail>();
        }
    
        public int ImportPaperId { get; set; }
        public string ImportPaperCode { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> AccountId { get; set; }
        public string Note { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImportPaperDetail> ImportPaperDetails { get; set; }
    }
}
