//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eLTMS.Web.DbConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class LabTestingIndex
    {
        public int LabtTestingIndexID { get; set; }
        public Nullable<int> LabTestingID { get; set; }
        public string IndexName { get; set; }
        public string IndexValue { get; set; }
        public string LowNormalHigh { get; set; }
        public string NormalRange { get; set; }
        public string Unit { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual LabTesting LabTesting { get; set; }
    }
}
