//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eLTMS.Web.DbConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class LabTesting
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LabTesting()
        {
            this.LabTestingIndexes = new HashSet<LabTestingIndex>();
        }
    
        public int LabTestingID { get; set; }
        public Nullable<int> LabTestID { get; set; }
        public Nullable<int> SampleGettingID { get; set; }
        public string Status { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> MachineSlot { get; set; }
    
        public virtual LabTest LabTest { get; set; }
        public virtual SampleGetting SampleGetting { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LabTestingIndex> LabTestingIndexes { get; set; }
    }
}
