

// ------------------------------------------------------------------------------------------------
// This code was generated by EntityFramework Reverse POCO Generator (http://www.reversepoco.com/).
// Created by Simon Hughes (https://about.me/simon.hughes).
//
// Do not make changes directly to this file - edit the template instead.
//
// The following connection settings were used to generate this file:
//     Configuration file:     "eLTMS.DataAccess\App.config"
//     Connection String Name: "FinalProjectContext"
//     Connection String:      "Data Source=DUCBMSE61791\LOCALDBINSTANCE;Initial Catalog=eLTMS-v5;User ID=sa;password=**zapped**;"
// ------------------------------------------------------------------------------------------------
// Database Edition       : Developer Edition (64-bit)
// Database Engine Edition: Enterprise

//Customized By: Hoangpn
// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace eLTMS.DataAccess.Models
{
  
    using System.Linq;

    #region POCO classes
     public interface IDbModel 
     {
		string CreatedBy { get; set; } // CreatedBy (length: 50)
		System.DateTime CreatedDate { get; set; } // CreatedDate
		string UpdatedBy { get; set; } // UpdatedBy (length: 50)
		System.DateTime UpdatedDate { get; set; } // UpdatedDate
	 } 



    // Token
    [Table("Token", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public class Token
    {
        [Column(@"TokenString", Order = 1, TypeName = "nvarchar(max)")]
        [Display(Name = "Token string")]
        public string TokenString { get; set; } // TokenString

        [Column(@"IsDeleted", Order = 2, TypeName = "bit")]
        [Display(Name = "Is deleted")]
        public bool? IsDeleted { get; set; } // IsDeleted

        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"TokenID", Order = 3, TypeName = "int")]
        [Index(@"PK_dbo.Token", 1, IsUnique = true, IsClustered = true)]
        [Index(@"PK__Token__658FEE8AE1B80E4B", 1, IsUnique = true, IsClustered = false)]
        [Required]
        [Key]
        [Display(Name = "Token ID")]
        public int TokenId { get; set; } // TokenID (Primary key)

        // Reverse navigation

        /// <summary>
        /// Child AccountTokens where [AccountToken].[TokenID] point to this entity (FK_dbo.AccountToken_dbo.Token_TokenID)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<AccountToken> AccountTokens { get; set; } // AccountToken.FK_dbo.AccountToken_dbo.Token_TokenID

        public Token()
        {
            AccountTokens = new System.Collections.Generic.List<AccountToken>();
        }
    }

    // Table
    [Table("Table", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public class Table
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"TableID", Order = 1, TypeName = "int")]
        [Index(@"PK_dbo.Table", 1, IsUnique = true, IsClustered = true)]
        [Index(@"PK_Table", 1, IsUnique = true, IsClustered = false)]
        [Required]
        [Key]
        [Display(Name = "Table ID")]
        public int TableId { get; set; } // TableID (Primary key)

        [Column(@"SampleGroupID", Order = 2, TypeName = "int")]
        [Index(@"IX_SampleGroupID", 1, IsUnique = false, IsClustered = false)]
        [Display(Name = "Sample group ID")]
        public int? SampleGroupId { get; set; } // SampleGroupID

        [Column(@"TableName", Order = 3, TypeName = "nchar")]
        [MaxLength(10)]
        [StringLength(10)]
        [Display(Name = "Table name")]
        public string TableName { get; set; } // TableName (length: 10)

        [Column(@"IsDeleted", Order = 4, TypeName = "bit")]
        [Display(Name = "Is deleted")]
        public bool? IsDeleted { get; set; } // IsDeleted

        // Reverse navigation

        /// <summary>
        /// Child SampleGettings where [SampleGetting].[TableID] point to this entity (FK_dbo.SampleGetting_dbo.Table_TableID)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<SampleGetting> SampleGettings { get; set; } // SampleGetting.FK_dbo.SampleGetting_dbo.Table_TableID

        // Foreign keys

        /// <summary>
        /// Parent SampleGroup pointed by [Table].([SampleGroupId]) (FK_dbo.Table_dbo.SampleGroup_SampleGroupID)
        /// </summary>
        [ForeignKey("SampleGroupId")] public virtual SampleGroup SampleGroup { get; set; } // FK_dbo.Table_dbo.SampleGroup_SampleGroupID

        public Table()
        {
            SampleGettings = new System.Collections.Generic.List<SampleGetting>();
        }
    }

    // SupplyType
    [Table("SupplyType", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public class SupplyType
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"SuppliesTypeId", Order = 1, TypeName = "int")]
        [Index(@"PK_dbo.SupplyType", 1, IsUnique = true, IsClustered = true)]
        [Index(@"PK_SuppliesType", 1, IsUnique = true, IsClustered = false)]
        [Required]
        [Key]
        [Display(Name = "Supplies type ID")]
        public int SuppliesTypeId { get; set; } // SuppliesTypeId (Primary key)

        [Column(@"SuppliesTypeName", Order = 2, TypeName = "nvarchar")]
        [MaxLength(50)]
        [StringLength(50)]
        [Display(Name = "Supplies type name")]
        public string SuppliesTypeName { get; set; } // SuppliesTypeName (length: 50)

        [Column(@"IsDeleted", Order = 3, TypeName = "bit")]
        [Display(Name = "Is deleted")]
        public bool? IsDeleted { get; set; } // IsDeleted

        // Reverse navigation

        /// <summary>
        /// Child Supplies where [Supply].[SuppliesTypeId] point to this entity (FK_dbo.Supply_dbo.SupplyType_SuppliesTypeId)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Supply> Supplies { get; set; } // Supply.FK_dbo.Supply_dbo.SupplyType_SuppliesTypeId

        public SupplyType()
        {
            Supplies = new System.Collections.Generic.List<Supply>();
        }
    }

    // Supply
    [Table("Supply", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public class Supply
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"SuppliesId", Order = 1, TypeName = "int")]
        [Index(@"PK_dbo.Supply", 1, IsUnique = true, IsClustered = true)]
        [Index(@"PK_Supplies", 1, IsUnique = true, IsClustered = false)]
        [Required]
        [Key]
        [Display(Name = "Supplies ID")]
        public int SuppliesId { get; set; } // SuppliesId (Primary key)

        [Column(@"SuppliesCode", Order = 2, TypeName = "nvarchar")]
        [MaxLength(50)]
        [StringLength(50)]
        [Display(Name = "Supplies code")]
        public string SuppliesCode { get; set; } // SuppliesCode (length: 50)

        [Column(@"SuppliesName", Order = 3, TypeName = "nvarchar")]
        [MaxLength(50)]
        [StringLength(50)]
        [Display(Name = "Supplies name")]
        public string SuppliesName { get; set; } // SuppliesName (length: 50)

        [Column(@"SuppliesTypeId", Order = 4, TypeName = "int")]
        [Index(@"IX_SuppliesTypeId", 1, IsUnique = false, IsClustered = false)]
        [Display(Name = "Supplies type ID")]
        public int? SuppliesTypeId { get; set; } // SuppliesTypeId

        [Column(@"Quantity", Order = 5, TypeName = "int")]
        [Display(Name = "Quantity")]
        public int? Quantity { get; set; } // Quantity

        [Column(@"Unit", Order = 6, TypeName = "nvarchar")]
        [MaxLength(20)]
        [StringLength(20)]
        [Display(Name = "Unit")]
        public string Unit { get; set; } // Unit (length: 20)

        [Column(@"Note", Order = 7, TypeName = "nvarchar(max)")]
        [Display(Name = "Note")]
        public string Note { get; set; } // Note

        [Column(@"IsDeleted", Order = 8, TypeName = "bit")]
        [Display(Name = "Is deleted")]
        public bool? IsDeleted { get; set; } // IsDeleted

        // Reverse navigation

        /// <summary>
        /// Child ExportPaperDetails where [ExportPaperDetail].[SuppliesId] point to this entity (FK_dbo.ExportPaperDetail_dbo.Supply_SuppliesId)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<ExportPaperDetail> ExportPaperDetails { get; set; } // ExportPaperDetail.FK_dbo.ExportPaperDetail_dbo.Supply_SuppliesId
        /// <summary>
        /// Child ImportPaperDetails where [ImportPaperDetail].[SuppliesId] point to this entity (FK_dbo.ImportPaperDetail_dbo.Supply_SuppliesId)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<ImportPaperDetail> ImportPaperDetails { get; set; } // ImportPaperDetail.FK_dbo.ImportPaperDetail_dbo.Supply_SuppliesId

        // Foreign keys

        /// <summary>
        /// Parent SupplyType pointed by [Supply].([SuppliesTypeId]) (FK_dbo.Supply_dbo.SupplyType_SuppliesTypeId)
        /// </summary>
        [ForeignKey("SuppliesTypeId")] public virtual SupplyType SupplyType { get; set; } // FK_dbo.Supply_dbo.SupplyType_SuppliesTypeId

        public Supply()
        {
            ExportPaperDetails = new System.Collections.Generic.List<ExportPaperDetail>();
            ImportPaperDetails = new System.Collections.Generic.List<ImportPaperDetail>();
        }
    }

    // Slot
    [Table("Slot", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public class Slot
    {
        [Column(@"StartTime", Order = 1, TypeName = "int")]
        [Display(Name = "Start time")]
        public int? StartTime { get; set; } // StartTime

        [Column(@"FinishTime", Order = 2, TypeName = "int")]
        [Display(Name = "Finish time")]
        public int? FinishTime { get; set; } // FinishTime

        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"SlotID", Order = 3, TypeName = "int")]
        [Index(@"PK_dbo.Slot", 1, IsUnique = true, IsClustered = true)]
        [Index(@"PK__Slot__0A124A4F1ED30403", 1, IsUnique = true, IsClustered = false)]
        [Required]
        [Key]
        [Display(Name = "Slot ID")]
        public int SlotId { get; set; } // SlotID (Primary key)

        [Column(@"SlotName", Order = 4, TypeName = "nvarchar")]
        [MaxLength(10)]
        [StringLength(10)]
        [Display(Name = "Slot name")]
        public string SlotName { get; set; } // SlotName (length: 10)

        [Column(@"SampleGroupId", Order = 5, TypeName = "int")]
        [Index(@"IX_SampleGroupId", 1, IsUnique = false, IsClustered = false)]
        [Display(Name = "Sample group ID")]
        public int? SampleGroupId { get; set; } // SampleGroupId

        [Column(@"IsDeleted", Order = 6, TypeName = "bit")]
        [Display(Name = "Is deleted")]
        public bool? IsDeleted { get; set; } // IsDeleted

        // Reverse navigation

        /// <summary>
        /// Child SampleGettings where [SampleGetting].[SlotID] point to this entity (FK_dbo.SampleGetting_dbo.Slot_SlotID)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<SampleGetting> SampleGettings { get; set; } // SampleGetting.FK_dbo.SampleGetting_dbo.Slot_SlotID

        // Foreign keys

        /// <summary>
        /// Parent SampleGroup pointed by [Slot].([SampleGroupId]) (FK_dbo.Slot_dbo.SampleGroup_SampleGroupId)
        /// </summary>
        [ForeignKey("SampleGroupId")] public virtual SampleGroup SampleGroup { get; set; } // FK_dbo.Slot_dbo.SampleGroup_SampleGroupId

        public Slot()
        {
            SampleGettings = new System.Collections.Generic.List<SampleGetting>();
        }
    }

    // SampleGroup
    [Table("SampleGroup", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public class SampleGroup
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"SampleGroupID", Order = 1, TypeName = "int")]
        [Index(@"PK_dbo.SampleGroup", 1, IsUnique = true, IsClustered = true)]
        [Index(@"PK_SampleGroup", 1, IsUnique = true, IsClustered = false)]
        [Required]
        [Key]
        [Display(Name = "Sample group ID")]
        public int SampleGroupId { get; set; } // SampleGroupID (Primary key)

        [Column(@"GroupName", Order = 2, TypeName = "nvarchar")]
        [MaxLength(100)]
        [StringLength(100)]
        [Display(Name = "Group name")]
        public string GroupName { get; set; } // GroupName (length: 100)

        [Column(@"GettingDuration", Order = 3, TypeName = "int")]
        [Display(Name = "Getting duration")]
        public int? GettingDuration { get; set; } // GettingDuration

        [Column(@"OpenTime", Order = 4, TypeName = "int")]
        [Display(Name = "Open time")]
        public int? OpenTime { get; set; } // OpenTime

        [Column(@"CloseTime", Order = 5, TypeName = "int")]
        [Display(Name = "Close time")]
        public int? CloseTime { get; set; } // CloseTime

        [Column(@"IsDeleted", Order = 6, TypeName = "bit")]
        [Display(Name = "Is deleted")]
        public bool? IsDeleted { get; set; } // IsDeleted

        // Reverse navigation

        /// <summary>
        /// Child Samples where [Sample].[SampleGroupID] point to this entity (FK_dbo.Sample_dbo.SampleGroup_SampleGroupID)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Sample> Samples { get; set; } // Sample.FK_dbo.Sample_dbo.SampleGroup_SampleGroupID
        /// <summary>
        /// Child Slots where [Slot].[SampleGroupId] point to this entity (FK_dbo.Slot_dbo.SampleGroup_SampleGroupId)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Slot> Slots { get; set; } // Slot.FK_dbo.Slot_dbo.SampleGroup_SampleGroupId
        /// <summary>
        /// Child Tables where [Table].[SampleGroupID] point to this entity (FK_dbo.Table_dbo.SampleGroup_SampleGroupID)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Table> Tables { get; set; } // Table.FK_dbo.Table_dbo.SampleGroup_SampleGroupID

        public SampleGroup()
        {
            Samples = new System.Collections.Generic.List<Sample>();
            Slots = new System.Collections.Generic.List<Slot>();
            Tables = new System.Collections.Generic.List<Table>();
        }
    }

    // SampleGetting
    [Table("SampleGetting", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public class SampleGetting
    {
        [Column(@"AppointmentID", Order = 1, TypeName = "int")]
        [Index(@"IX_AppointmentID", 1, IsUnique = false, IsClustered = false)]
        [Display(Name = "Appointment ID")]
        public int? AppointmentId { get; set; } // AppointmentID

        [Column(@"SampleID", Order = 2, TypeName = "int")]
        [Index(@"IX_SampleID", 1, IsUnique = false, IsClustered = false)]
        [Display(Name = "Sample ID")]
        public int? SampleId { get; set; } // SampleID

        [Column(@"Status", Order = 3, TypeName = "nvarchar")]
        [MaxLength(20)]
        [StringLength(20)]
        [Display(Name = "Status")]
        public string Status { get; set; } // Status (length: 20)

        [Column(@"IsDeleted", Order = 4, TypeName = "bit")]
        [Display(Name = "Is deleted")]
        public bool? IsDeleted { get; set; } // IsDeleted

        [Column(@"SampleGettingCode", Order = 5, TypeName = "nvarchar")]
        [MaxLength(20)]
        [StringLength(20)]
        [Display(Name = "Sample getting code")]
        public string SampleGettingCode { get; set; } // SampleGettingCode (length: 20)

        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"SampleGettingID", Order = 6, TypeName = "int")]
        [Index(@"PK_dbo.SampleGetting", 1, IsUnique = true, IsClustered = true)]
        [Index(@"PK__SampleGe__366AD1F732C6FE55", 1, IsUnique = true, IsClustered = false)]
        [Required]
        [Key]
        [Display(Name = "Sample getting ID")]
        public int SampleGettingId { get; set; } // SampleGettingID (Primary key)

        [Column(@"IsPaid", Order = 7, TypeName = "bit")]
        [Display(Name = "Is paid")]
        public bool? IsPaid { get; set; } // IsPaid

        [Column(@"TableID", Order = 8, TypeName = "int")]
        [Index(@"IX_TableID", 1, IsUnique = false, IsClustered = false)]
        [Display(Name = "Table ID")]
        public int? TableId { get; set; } // TableID

        [Column(@"SlotID", Order = 9, TypeName = "int")]
        [Index(@"IX_SlotID", 1, IsUnique = false, IsClustered = false)]
        [Display(Name = "Slot ID")]
        public int? SlotId { get; set; } // SlotID

        [Column(@"GettingDate", Order = 10, TypeName = "date")]
        [Display(Name = "Getting date")]
        public System.DateTime? GettingDate { get; set; } // GettingDate

        [Column(@"OrderNumber", Order = 11, TypeName = "int")]
        [Display(Name = "Order number")]
        public int? OrderNumber { get; set; } // OrderNumber

        [Column(@"IsGot", Order = 12, TypeName = "bit")]
        [Display(Name = "Is got")]
        public bool? IsGot { get; set; } // IsGot

        // Reverse navigation

        /// <summary>
        /// Child LabTestings where [LabTesting].[SampleGettingID] point to this entity (FK_dbo.LabTesting_dbo.SampleGetting_SampleGettingID)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<LabTesting> LabTestings { get; set; } // LabTesting.FK_dbo.LabTesting_dbo.SampleGetting_SampleGettingID

        // Foreign keys

        /// <summary>
        /// Parent Appointment pointed by [SampleGetting].([AppointmentId]) (FK_dbo.SampleGetting_dbo.Appointment_AppointmentID)
        /// </summary>
        [ForeignKey("AppointmentId")] public virtual Appointment Appointment { get; set; } // FK_dbo.SampleGetting_dbo.Appointment_AppointmentID

        /// <summary>
        /// Parent Sample pointed by [SampleGetting].([SampleId]) (FK_dbo.SampleGetting_dbo.Sample_SampleID)
        /// </summary>
        [ForeignKey("SampleId")] public virtual Sample Sample { get; set; } // FK_dbo.SampleGetting_dbo.Sample_SampleID

        /// <summary>
        /// Parent Slot pointed by [SampleGetting].([SlotId]) (FK_dbo.SampleGetting_dbo.Slot_SlotID)
        /// </summary>
        [ForeignKey("SlotId")] public virtual Slot Slot { get; set; } // FK_dbo.SampleGetting_dbo.Slot_SlotID

        /// <summary>
        /// Parent Table pointed by [SampleGetting].([TableId]) (FK_dbo.SampleGetting_dbo.Table_TableID)
        /// </summary>
        [ForeignKey("TableId")] public virtual Table Table { get; set; } // FK_dbo.SampleGetting_dbo.Table_TableID

        public SampleGetting()
        {
            LabTestings = new System.Collections.Generic.List<LabTesting>();
        }
    }

    // Sample
    [Table("Sample", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public class Sample
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"SampleID", Order = 1, TypeName = "int")]
        [Index(@"PK_dbo.Sample", 1, IsUnique = true, IsClustered = true)]
        [Index(@"PK_Sample", 1, IsUnique = true, IsClustered = false)]
        [Required]
        [Key]
        [Display(Name = "Sample ID")]
        public int SampleId { get; set; } // SampleID (Primary key)

        [Column(@"SampleGroupID", Order = 2, TypeName = "int")]
        [Index(@"IX_SampleGroupID", 1, IsUnique = false, IsClustered = false)]
        [Display(Name = "Sample group ID")]
        public int? SampleGroupId { get; set; } // SampleGroupID

        [Column(@"SampleName", Order = 3, TypeName = "nvarchar")]
        [MaxLength(20)]
        [StringLength(20)]
        [Display(Name = "Sample name")]
        public string SampleName { get; set; } // SampleName (length: 20)

        [Column(@"Description", Order = 4, TypeName = "nvarchar")]
        [MaxLength(500)]
        [StringLength(500)]
        [Display(Name = "Description")]
        public string Description { get; set; } // Description (length: 500)

        [Column(@"IsDeleted", Order = 5, TypeName = "bit")]
        [Display(Name = "Is deleted")]
        public bool? IsDeleted { get; set; } // IsDeleted

        // Reverse navigation

        /// <summary>
        /// Child LabTests where [LabTest].[SampleID] point to this entity (FK_dbo.LabTest_dbo.Sample_SampleID)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<LabTest> LabTests { get; set; } // LabTest.FK_dbo.LabTest_dbo.Sample_SampleID
        /// <summary>
        /// Child SampleGettings where [SampleGetting].[SampleID] point to this entity (FK_dbo.SampleGetting_dbo.Sample_SampleID)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<SampleGetting> SampleGettings { get; set; } // SampleGetting.FK_dbo.SampleGetting_dbo.Sample_SampleID

        // Foreign keys

        /// <summary>
        /// Parent SampleGroup pointed by [Sample].([SampleGroupId]) (FK_dbo.Sample_dbo.SampleGroup_SampleGroupID)
        /// </summary>
        [ForeignKey("SampleGroupId")] public virtual SampleGroup SampleGroup { get; set; } // FK_dbo.Sample_dbo.SampleGroup_SampleGroupID

        public Sample()
        {
            SampleGettings = new System.Collections.Generic.List<SampleGetting>();
            LabTests = new System.Collections.Generic.List<LabTest>();
        }
    }

    // Role
    [Table("Role", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public class Role
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"RoleID", Order = 1, TypeName = "int")]
        [Index(@"PK_dbo.Role", 1, IsUnique = true, IsClustered = true)]
        [Index(@"PK_Role", 1, IsUnique = true, IsClustered = false)]
        [Required]
        [Key]
        [Display(Name = "Role ID")]
        public int RoleId { get; set; } // RoleID (Primary key)

        [Column(@"RoleName", Order = 2, TypeName = "nvarchar")]
        [MaxLength(20)]
        [StringLength(20)]
        [Display(Name = "Role name")]
        public string RoleName { get; set; } // RoleName (length: 20)

        // Reverse navigation

        /// <summary>
        /// Child Accounts where [Account].[RoleID] point to this entity (FK_dbo.Account_dbo.Role_RoleID)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Account> Accounts { get; set; } // Account.FK_dbo.Account_dbo.Role_RoleID

        public Role()
        {
            Accounts = new System.Collections.Generic.List<Account>();
        }
    }

    // PatientAccount
    [Table("PatientAccount", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public class PatientAccount
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"PatientAccountID", Order = 1, TypeName = "int")]
        [Index(@"PK_dbo.PatientAccount", 1, IsUnique = true, IsClustered = true)]
        [Index(@"PK__PatientA__048CB9917D834ECE", 1, IsUnique = true, IsClustered = false)]
        [Required]
        [Key]
        [Display(Name = "Patient account ID")]
        public int PatientAccountId { get; set; } // PatientAccountID (Primary key)

        [Column(@"AccountID", Order = 2, TypeName = "int")]
        [Index(@"IX_AccountID", 1, IsUnique = false, IsClustered = false)]
        [Required]
        [Display(Name = "Account ID")]
        public int AccountId { get; set; } // AccountID

        [Column(@"PatientID", Order = 3, TypeName = "int")]
        [Index(@"IX_PatientID", 1, IsUnique = false, IsClustered = false)]
        [Required]
        [Display(Name = "Patient ID")]
        public int PatientId { get; set; } // PatientID

        [Column(@"IsDeleted", Order = 4, TypeName = "bit")]
        [Display(Name = "Is deleted")]
        public bool? IsDeleted { get; set; } // IsDeleted

        // Foreign keys

        /// <summary>
        /// Parent Account pointed by [PatientAccount].([AccountId]) (FK_dbo.PatientAccount_dbo.Account_AccountID)
        /// </summary>
        [ForeignKey("AccountId"), Required] public virtual Account Account { get; set; } // FK_dbo.PatientAccount_dbo.Account_AccountID

        /// <summary>
        /// Parent Patient pointed by [PatientAccount].([PatientId]) (FK_dbo.PatientAccount_dbo.Patient_PatientID)
        /// </summary>
        [ForeignKey("PatientId"), Required] public virtual Patient Patient { get; set; } // FK_dbo.PatientAccount_dbo.Patient_PatientID
    }

    // Patient
    [Table("Patient", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public class Patient
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"PatientID", Order = 1, TypeName = "int")]
        [Index(@"PK_dbo.Patient", 1, IsUnique = true, IsClustered = true)]
        [Index(@"PK__Patient__3214EC2761CA8559", 1, IsUnique = true, IsClustered = false)]
        [Required]
        [Key]
        [Display(Name = "Patient ID")]
        public int PatientId { get; set; } // PatientID (Primary key)

        [Column(@"PatientCode", Order = 2, TypeName = "nvarchar")]
        [MaxLength(20)]
        [StringLength(20)]
        [Display(Name = "Patient code")]
        public string PatientCode { get; set; } // PatientCode (length: 20)

        [Column(@"AccountID", Order = 3, TypeName = "int")]
        [Display(Name = "Account ID")]
        public int? AccountId { get; set; } // AccountID

        [Column(@"FullName", Order = 4, TypeName = "nvarchar")]
        [MaxLength(100)]
        [StringLength(100)]
        [Display(Name = "Full name")]
        public string FullName { get; set; } // FullName (length: 100)

        [Column(@"Gender", Order = 5, TypeName = "nvarchar")]
        [MaxLength(10)]
        [StringLength(10)]
        [Display(Name = "Gender")]
        public string Gender { get; set; } // Gender (length: 10)

        [Column(@"DateOfBirth", Order = 6, TypeName = "date")]
        [Display(Name = "Date of birth")]
        public System.DateTime? DateOfBirth { get; set; } // DateOfBirth

        [Column(@"PhoneNumber", Order = 7, TypeName = "nvarchar")]
        [MaxLength(20)]
        [StringLength(20)]
        [Phone]
        [Display(Name = "Phone number")]
        public string PhoneNumber { get; set; } // PhoneNumber (length: 20)

        [Column(@"HomeAddress", Order = 8, TypeName = "nvarchar")]
        [MaxLength(200)]
        [StringLength(200)]
        [Display(Name = "Home address")]
        public string HomeAddress { get; set; } // HomeAddress (length: 200)

        [Column(@"CompanyAddress", Order = 9, TypeName = "nvarchar")]
        [MaxLength(200)]
        [StringLength(200)]
        [Display(Name = "Company address")]
        public string CompanyAddress { get; set; } // CompanyAddress (length: 200)

        [Column(@"IsDeleted", Order = 10, TypeName = "bit")]
        [Display(Name = "Is deleted")]
        public bool? IsDeleted { get; set; } // IsDeleted

        [Column(@"IsOnline", Order = 11, TypeName = "bit")]
        [Display(Name = "Is online")]
        public bool? IsOnline { get; set; } // IsOnline

        [Column(@"IdentityCardNumber", Order = 12, TypeName = "nvarchar")]
        [MaxLength(20)]
        [StringLength(20)]
        [Display(Name = "Identity card number")]
        public string IdentityCardNumber { get; set; } // IdentityCardNumber (length: 20)

        // Reverse navigation

        /// <summary>
        /// Child Appointments where [Appointment].[PatientID] point to this entity (FK_dbo.Appointment_dbo.Patient_PatientID)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Appointment> Appointments { get; set; } // Appointment.FK_dbo.Appointment_dbo.Patient_PatientID
        /// <summary>
        /// Child Feedbacks where [Feedback].[PatientID] point to this entity (FK_dbo.Feedback_dbo.Patient_PatientID)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Feedback> Feedbacks { get; set; } // Feedback.FK_dbo.Feedback_dbo.Patient_PatientID
        /// <summary>
        /// Child PatientAccounts where [PatientAccount].[PatientID] point to this entity (FK_dbo.PatientAccount_dbo.Patient_PatientID)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<PatientAccount> PatientAccounts { get; set; } // PatientAccount.FK_dbo.PatientAccount_dbo.Patient_PatientID

        public Patient()
        {
            Appointments = new System.Collections.Generic.List<Appointment>();
            Feedbacks = new System.Collections.Generic.List<Feedback>();
            PatientAccounts = new System.Collections.Generic.List<PatientAccount>();
        }
    }

    // LabTestingIndex
    [Table("LabTestingIndex", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public class LabTestingIndex
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"LabtTestingIndexID", Order = 1, TypeName = "int")]
        [Index(@"PK_dbo.LabTestingIndex", 1, IsUnique = true, IsClustered = true)]
        [Index(@"PK__ResultIn__64F89096C59FFD89", 1, IsUnique = true, IsClustered = false)]
        [Required]
        [Key]
        [Display(Name = "Labt testing index ID")]
        public int LabtTestingIndexId { get; set; } // LabtTestingIndexID (Primary key)

        [Column(@"LabTestingID", Order = 2, TypeName = "int")]
        [Index(@"IX_LabTestingID", 1, IsUnique = false, IsClustered = false)]
        [Display(Name = "Lab testing ID")]
        public int? LabTestingId { get; set; } // LabTestingID

        [Column(@"IndexName", Order = 3, TypeName = "nvarchar")]
        [MaxLength(20)]
        [StringLength(20)]
        [Display(Name = "Index name")]
        public string IndexName { get; set; } // IndexName (length: 20)

        [Column(@"IndexValue", Order = 4, TypeName = "nvarchar")]
        [MaxLength(50)]
        [StringLength(50)]
        [Display(Name = "Index value")]
        public string IndexValue { get; set; } // IndexValue (length: 50)

        [Column(@"LowNormalHigh", Order = 5, TypeName = "nvarchar")]
        [MaxLength(10)]
        [StringLength(10)]
        [Display(Name = "Low normal high")]
        public string LowNormalHigh { get; set; } // LowNormalHigh (length: 10)

        [Column(@"NormalRange", Order = 6, TypeName = "nvarchar")]
        [MaxLength(50)]
        [StringLength(50)]
        [Display(Name = "Normal range")]
        public string NormalRange { get; set; } // NormalRange (length: 50)

        [Column(@"Unit", Order = 7, TypeName = "nvarchar")]
        [MaxLength(20)]
        [StringLength(20)]
        [Display(Name = "Unit")]
        public string Unit { get; set; } // Unit (length: 20)

        [Column(@"IsDeleted", Order = 8, TypeName = "bit")]
        [Display(Name = "Is deleted")]
        public bool? IsDeleted { get; set; } // IsDeleted

        // Foreign keys

        /// <summary>
        /// Parent LabTesting pointed by [LabTestingIndex].([LabTestingId]) (FK_dbo.LabTestingIndex_dbo.LabTesting_LabTestingID)
        /// </summary>
        [ForeignKey("LabTestingId")] public virtual LabTesting LabTesting { get; set; } // FK_dbo.LabTestingIndex_dbo.LabTesting_LabTestingID
    }

    // LabTesting
    [Table("LabTesting", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public class LabTesting
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"LabTestingID", Order = 1, TypeName = "int")]
        [Index(@"PK_dbo.LabTesting", 1, IsUnique = true, IsClustered = true)]
        [Index(@"PK_LabTesting", 1, IsUnique = true, IsClustered = false)]
        [Required]
        [Key]
        [Display(Name = "Lab testing ID")]
        public int LabTestingId { get; set; } // LabTestingID (Primary key)

        [Column(@"LabTestID", Order = 2, TypeName = "int")]
        [Index(@"IX_LabTestID", 1, IsUnique = false, IsClustered = false)]
        [Display(Name = "Lab test ID")]
        public int? LabTestId { get; set; } // LabTestID

        [Column(@"SampleGettingID", Order = 3, TypeName = "int")]
        [Index(@"IX_SampleGettingID", 1, IsUnique = false, IsClustered = false)]
        [Display(Name = "Sample getting ID")]
        public int? SampleGettingId { get; set; } // SampleGettingID

        [Column(@"Status", Order = 4, TypeName = "nvarchar")]
        [MaxLength(20)]
        [StringLength(20)]
        [Display(Name = "Status")]
        public string Status { get; set; } // Status (length: 20)

        [Column(@"IsDeleted", Order = 5, TypeName = "bit")]
        [Display(Name = "Is deleted")]
        public bool? IsDeleted { get; set; } // IsDeleted

        [Column(@"MachineSlot", Order = 6, TypeName = "int")]
        [Display(Name = "Machine slot")]
        public int? MachineSlot { get; set; } // MachineSlot

        // Reverse navigation

        /// <summary>
        /// Child LabTestingIndexes where [LabTestingIndex].[LabTestingID] point to this entity (FK_dbo.LabTestingIndex_dbo.LabTesting_LabTestingID)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<LabTestingIndex> LabTestingIndexes { get; set; } // LabTestingIndex.FK_dbo.LabTestingIndex_dbo.LabTesting_LabTestingID

        // Foreign keys

        /// <summary>
        /// Parent LabTest pointed by [LabTesting].([LabTestId]) (FK_dbo.LabTesting_dbo.LabTest_LabTestID)
        /// </summary>
        [ForeignKey("LabTestId")] public virtual LabTest LabTest { get; set; } // FK_dbo.LabTesting_dbo.LabTest_LabTestID

        /// <summary>
        /// Parent SampleGetting pointed by [LabTesting].([SampleGettingId]) (FK_dbo.LabTesting_dbo.SampleGetting_SampleGettingID)
        /// </summary>
        [ForeignKey("SampleGettingId")] public virtual SampleGetting SampleGetting { get; set; } // FK_dbo.LabTesting_dbo.SampleGetting_SampleGettingID

        public LabTesting()
        {
            LabTestingIndexes = new System.Collections.Generic.List<LabTestingIndex>();
        }
    }

    // LabTest
    [Table("LabTest", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public class LabTest
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"LabTestID", Order = 1, TypeName = "int")]
        [Index(@"PK_dbo.LabTest", 1, IsUnique = true, IsClustered = true)]
        [Index(@"PK_TestType", 1, IsUnique = true, IsClustered = false)]
        [Required]
        [Key]
        [Display(Name = "Lab test ID")]
        public int LabTestId { get; set; } // LabTestID (Primary key)

        [Column(@"LabTestCode", Order = 2, TypeName = "nvarchar")]
        [MaxLength(20)]
        [StringLength(20)]
        [Display(Name = "Lab test code")]
        public string LabTestCode { get; set; } // LabTestCode (length: 20)

        [Column(@"LabTestName", Order = 3, TypeName = "nvarchar")]
        [MaxLength(100)]
        [StringLength(100)]
        [Display(Name = "Lab test name")]
        public string LabTestName { get; set; } // LabTestName (length: 100)

        [Column(@"Description", Order = 4, TypeName = "nvarchar")]
        [MaxLength(500)]
        [StringLength(500)]
        [Display(Name = "Description")]
        public string Description { get; set; } // Description (length: 500)

        [Column(@"Price", Order = 5, TypeName = "int")]
        [Display(Name = "Price")]
        public int? Price { get; set; } // Price

        [Column(@"IsDeleted", Order = 6, TypeName = "bit")]
        [Display(Name = "Is deleted")]
        public bool? IsDeleted { get; set; } // IsDeleted

        [Column(@"SampleID", Order = 7, TypeName = "int")]
        [Index(@"IX_SampleID", 1, IsUnique = false, IsClustered = false)]
        [Display(Name = "Sample ID")]
        public int? SampleId { get; set; } // SampleID

        // Reverse navigation

        /// <summary>
        /// Child LabTestings where [LabTesting].[LabTestID] point to this entity (FK_dbo.LabTesting_dbo.LabTest_LabTestID)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<LabTesting> LabTestings { get; set; } // LabTesting.FK_dbo.LabTesting_dbo.LabTest_LabTestID

        // Foreign keys

        /// <summary>
        /// Parent Sample pointed by [LabTest].([SampleId]) (FK_dbo.LabTest_dbo.Sample_SampleID)
        /// </summary>
        [ForeignKey("SampleId")] public virtual Sample Sample { get; set; } // FK_dbo.LabTest_dbo.Sample_SampleID

        public LabTest()
        {
            LabTestings = new System.Collections.Generic.List<LabTesting>();
        }
    }

    // ImportPaperDetail
    [Table("ImportPaperDetail", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public class ImportPaperDetail
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"ImportPaperDetailId", Order = 1, TypeName = "int")]
        [Index(@"PK_dbo.ImportPaperDetail", 1, IsUnique = true, IsClustered = true)]
        [Index(@"PK_InputPaperDetail", 1, IsUnique = true, IsClustered = false)]
        [Required]
        [Key]
        [Display(Name = "Import paper detail ID")]
        public int ImportPaperDetailId { get; set; } // ImportPaperDetailId (Primary key)

        [Column(@"ImportPaperId", Order = 2, TypeName = "int")]
        [Index(@"IX_ImportPaperId", 1, IsUnique = false, IsClustered = false)]
        [Display(Name = "Import paper ID")]
        public int? ImportPaperId { get; set; } // ImportPaperId

        [Column(@"SuppliesId", Order = 3, TypeName = "int")]
        [Index(@"IX_SuppliesId", 1, IsUnique = false, IsClustered = false)]
        [Display(Name = "Supplies ID")]
        public int? SuppliesId { get; set; } // SuppliesId

        [Column(@"Unit", Order = 4, TypeName = "nvarchar")]
        [MaxLength(50)]
        [StringLength(50)]
        [Display(Name = "Unit")]
        public string Unit { get; set; } // Unit (length: 50)

        [Column(@"Quantity", Order = 5, TypeName = "int")]
        [Display(Name = "Quantity")]
        public int? Quantity { get; set; } // Quantity

        [Column(@"Note", Order = 6, TypeName = "nvarchar(max)")]
        [Display(Name = "Note")]
        public string Note { get; set; } // Note

        [Column(@"IsDeleted", Order = 7, TypeName = "bit")]
        [Display(Name = "Is deleted")]
        public bool? IsDeleted { get; set; } // IsDeleted

        // Foreign keys

        /// <summary>
        /// Parent ImportPaper pointed by [ImportPaperDetail].([ImportPaperId]) (FK_dbo.ImportPaperDetail_dbo.ImportPaper_ImportPaperId)
        /// </summary>
        [ForeignKey("ImportPaperId")] public virtual ImportPaper ImportPaper { get; set; } // FK_dbo.ImportPaperDetail_dbo.ImportPaper_ImportPaperId

        /// <summary>
        /// Parent Supply pointed by [ImportPaperDetail].([SuppliesId]) (FK_dbo.ImportPaperDetail_dbo.Supply_SuppliesId)
        /// </summary>
        [ForeignKey("SuppliesId")] public virtual Supply Supply { get; set; } // FK_dbo.ImportPaperDetail_dbo.Supply_SuppliesId
    }

    // ImportPaper
    [Table("ImportPaper", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public class ImportPaper
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"ImportPaperId", Order = 1, TypeName = "int")]
        [Index(@"PK_dbo.ImportPaper", 1, IsUnique = true, IsClustered = true)]
        [Index(@"PK_ImportPaper", 1, IsUnique = true, IsClustered = false)]
        [Required]
        [Key]
        [Display(Name = "Import paper ID")]
        public int ImportPaperId { get; set; } // ImportPaperId (Primary key)

        [Column(@"ImportPaperCode", Order = 2, TypeName = "nvarchar")]
        [MaxLength(20)]
        [StringLength(20)]
        [Display(Name = "Import paper code")]
        public string ImportPaperCode { get; set; } // ImportPaperCode (length: 20)

        [Column(@"CreateDate", Order = 3, TypeName = "datetime")]
        [Display(Name = "Create date")]
        public System.DateTime? CreateDate { get; set; } // CreateDate

        [Column(@"AccountId", Order = 4, TypeName = "int")]
        [Display(Name = "Account ID")]
        public int? AccountId { get; set; } // AccountId

        [Column(@"Note", Order = 5, TypeName = "nvarchar(max)")]
        [Display(Name = "Note")]
        public string Note { get; set; } // Note

        [Column(@"IsDeleted", Order = 6, TypeName = "bit")]
        [Display(Name = "Is deleted")]
        public bool? IsDeleted { get; set; } // IsDeleted

        // Reverse navigation

        /// <summary>
        /// Child ImportPaperDetails where [ImportPaperDetail].[ImportPaperId] point to this entity (FK_dbo.ImportPaperDetail_dbo.ImportPaper_ImportPaperId)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<ImportPaperDetail> ImportPaperDetails { get; set; } // ImportPaperDetail.FK_dbo.ImportPaperDetail_dbo.ImportPaper_ImportPaperId

        public ImportPaper()
        {
            ImportPaperDetails = new System.Collections.Generic.List<ImportPaperDetail>();
        }
    }

    // HospitalSuggestion
    [Table("HospitalSuggestion", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public class HospitalSuggestion
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"HospitalSuggestionID", Order = 1, TypeName = "int")]
        [Index(@"PK_dbo.HospitalSuggestion", 1, IsUnique = true, IsClustered = true)]
        [Index(@"PK__Hospital__3214EC2744CC6669", 1, IsUnique = true, IsClustered = false)]
        [Required]
        [Key]
        [Display(Name = "Hospital suggestion ID")]
        public int HospitalSuggestionId { get; set; } // HospitalSuggestionID (Primary key)

        [Column(@"DiseaseName", Order = 2, TypeName = "nvarchar(max)")]
        [Display(Name = "Disease name")]
        public string DiseaseName { get; set; } // DiseaseName

        [Column(@"HospitalList", Order = 3, TypeName = "nvarchar(max)")]
        [Display(Name = "Hospital list")]
        public string HospitalList { get; set; } // HospitalList

        [Column(@"HospitalAdd", Order = 4, TypeName = "nvarchar(max)")]
        [Display(Name = "Hospital add")]
        public string HospitalAdd { get; set; } // HospitalAdd

        [Column(@"HospitalPhone", Order = 5, TypeName = "nvarchar(max)")]
        [Display(Name = "Hospital phone")]
        public string HospitalPhone { get; set; } // HospitalPhone

        [Column(@"IsDeleted", Order = 6, TypeName = "bit")]
        [Display(Name = "Is deleted")]
        public bool? IsDeleted { get; set; } // IsDeleted
    }

    // Feedback
    [Table("Feedback", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public class Feedback
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"FeedbackID", Order = 1, TypeName = "int")]
        [Index(@"PK_dbo.Feedback", 1, IsUnique = true, IsClustered = true)]
        [Index(@"PK__Feedback__6A4BEDF66D5C3999", 1, IsUnique = true, IsClustered = false)]
        [Required]
        [Key]
        [Display(Name = "Feedback ID")]
        public int FeedbackId { get; set; } // FeedbackID (Primary key)

        [Column(@"PatientID", Order = 2, TypeName = "int")]
        [Index(@"IX_PatientID", 1, IsUnique = false, IsClustered = false)]
        [Display(Name = "Patient ID")]
        public int? PatientId { get; set; } // PatientID

        [Column(@"EmployeeID", Order = 3, TypeName = "int")]
        [Index(@"IX_EmployeeID", 1, IsUnique = false, IsClustered = false)]
        [Display(Name = "Employee ID")]
        public int? EmployeeId { get; set; } // EmployeeID

        [Column(@"Content", Order = 4, TypeName = "nvarchar")]
        [MaxLength(500)]
        [StringLength(500)]
        [Display(Name = "Content")]
        public string Content { get; set; } // Content (length: 500)

        [Column(@"ReceivedDateTime", Order = 5, TypeName = "datetime")]
        [Display(Name = "Received date time")]
        public System.DateTime? ReceivedDateTime { get; set; } // ReceivedDateTime

        [Column(@"IsDeleted", Order = 6, TypeName = "bit")]
        [Display(Name = "Is deleted")]
        public bool? IsDeleted { get; set; } // IsDeleted

        [Column(@"Status", Order = 7, TypeName = "nvarchar")]
        [MaxLength(100)]
        [StringLength(100)]
        [Display(Name = "Status")]
        public string Status { get; set; } // Status (length: 100)

        [Column(@"StarRating", Order = 8, TypeName = "int")]
        [Display(Name = "Star rating")]
        public int? StarRating { get; set; } // StarRating

        // Foreign keys

        /// <summary>
        /// Parent Employee pointed by [Feedback].([EmployeeId]) (FK_dbo.Feedback_dbo.Employee_EmployeeID)
        /// </summary>
        [ForeignKey("EmployeeId")] public virtual Employee Employee { get; set; } // FK_dbo.Feedback_dbo.Employee_EmployeeID

        /// <summary>
        /// Parent Patient pointed by [Feedback].([PatientId]) (FK_dbo.Feedback_dbo.Patient_PatientID)
        /// </summary>
        [ForeignKey("PatientId")] public virtual Patient Patient { get; set; } // FK_dbo.Feedback_dbo.Patient_PatientID
    }

    // ExportPaperDetail
    [Table("ExportPaperDetail", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public class ExportPaperDetail
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"ExportPaperDetailId", Order = 1, TypeName = "int")]
        [Index(@"PK_dbo.ExportPaperDetail", 1, IsUnique = true, IsClustered = true)]
        [Index(@"PK_ExportProposurePaperDetail", 1, IsUnique = true, IsClustered = false)]
        [Required]
        [Key]
        [Display(Name = "Export paper detail ID")]
        public int ExportPaperDetailId { get; set; } // ExportPaperDetailId (Primary key)

        [Column(@"ExportPaperId", Order = 2, TypeName = "int")]
        [Index(@"IX_ExportPaperId", 1, IsUnique = false, IsClustered = false)]
        [Display(Name = "Export paper ID")]
        public int? ExportPaperId { get; set; } // ExportPaperId

        [Column(@"SuppliesId", Order = 3, TypeName = "int")]
        [Index(@"IX_SuppliesId", 1, IsUnique = false, IsClustered = false)]
        [Display(Name = "Supplies ID")]
        public int? SuppliesId { get; set; } // SuppliesId

        [Column(@"Unit", Order = 4, TypeName = "nvarchar")]
        [MaxLength(50)]
        [StringLength(50)]
        [Display(Name = "Unit")]
        public string Unit { get; set; } // Unit (length: 50)

        [Column(@"Quantity", Order = 5, TypeName = "int")]
        [Display(Name = "Quantity")]
        public int? Quantity { get; set; } // Quantity

        [Column(@"Note", Order = 6, TypeName = "nvarchar(max)")]
        [Display(Name = "Note")]
        public string Note { get; set; } // Note

        [Column(@"IsDeleted", Order = 7, TypeName = "bit")]
        [Display(Name = "Is deleted")]
        public bool? IsDeleted { get; set; } // IsDeleted

        // Foreign keys

        /// <summary>
        /// Parent ExportPaper pointed by [ExportPaperDetail].([ExportPaperId]) (FK_dbo.ExportPaperDetail_dbo.ExportPaper_ExportPaperId)
        /// </summary>
        [ForeignKey("ExportPaperId")] public virtual ExportPaper ExportPaper { get; set; } // FK_dbo.ExportPaperDetail_dbo.ExportPaper_ExportPaperId

        /// <summary>
        /// Parent Supply pointed by [ExportPaperDetail].([SuppliesId]) (FK_dbo.ExportPaperDetail_dbo.Supply_SuppliesId)
        /// </summary>
        [ForeignKey("SuppliesId")] public virtual Supply Supply { get; set; } // FK_dbo.ExportPaperDetail_dbo.Supply_SuppliesId
    }

    // ExportPaper
    [Table("ExportPaper", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public class ExportPaper
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"ExportPaperId", Order = 1, TypeName = "int")]
        [Index(@"PK_dbo.ExportPaper", 1, IsUnique = true, IsClustered = true)]
        [Index(@"PK_ExportProposurePaper", 1, IsUnique = true, IsClustered = false)]
        [Required]
        [Key]
        [Display(Name = "Export paper ID")]
        public int ExportPaperId { get; set; } // ExportPaperId (Primary key)

        [Column(@"ExportPaperCode", Order = 2, TypeName = "nvarchar")]
        [MaxLength(20)]
        [StringLength(20)]
        [Display(Name = "Export paper code")]
        public string ExportPaperCode { get; set; } // ExportPaperCode (length: 20)

        [Column(@"CreateDate", Order = 3, TypeName = "datetime")]
        [Display(Name = "Create date")]
        public System.DateTime? CreateDate { get; set; } // CreateDate

        [Column(@"AccountId", Order = 4, TypeName = "int")]
        [Display(Name = "Account ID")]
        public int? AccountId { get; set; } // AccountId

        [Column(@"Note", Order = 5, TypeName = "nvarchar(max)")]
        [Display(Name = "Note")]
        public string Note { get; set; } // Note

        [Column(@"Status", Order = 6, TypeName = "bit")]
        [Display(Name = "Status")]
        public bool? Status { get; set; } // Status

        [Column(@"IsDeleted", Order = 7, TypeName = "bit")]
        [Display(Name = "Is deleted")]
        public bool? IsDeleted { get; set; } // IsDeleted

        // Reverse navigation

        /// <summary>
        /// Child ExportPaperDetails where [ExportPaperDetail].[ExportPaperId] point to this entity (FK_dbo.ExportPaperDetail_dbo.ExportPaper_ExportPaperId)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<ExportPaperDetail> ExportPaperDetails { get; set; } // ExportPaperDetail.FK_dbo.ExportPaperDetail_dbo.ExportPaper_ExportPaperId

        public ExportPaper()
        {
            ExportPaperDetails = new System.Collections.Generic.List<ExportPaperDetail>();
        }
    }

    // Employee
    [Table("Employee", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public class Employee
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"EmployeeID", Order = 1, TypeName = "int")]
        [Index(@"PK_dbo.Employee", 1, IsUnique = true, IsClustered = true)]
        [Index(@"PK__Employee__7AD04FF191E79CA7", 1, IsUnique = true, IsClustered = false)]
        [Required]
        [Key]
        [Display(Name = "Employee ID")]
        public int EmployeeId { get; set; } // EmployeeID (Primary key)

        [Column(@"AccountID", Order = 2, TypeName = "int")]
        [Index(@"IX_AccountID", 1, IsUnique = false, IsClustered = false)]
        [Display(Name = "Account ID")]
        public int? AccountId { get; set; } // AccountID

        [Column(@"Status", Order = 3, TypeName = "nvarchar")]
        [MaxLength(20)]
        [StringLength(20)]
        [Display(Name = "Status")]
        public string Status { get; set; } // Status (length: 20)

        [Column(@"FullName", Order = 4, TypeName = "nvarchar")]
        [MaxLength(100)]
        [StringLength(100)]
        [Display(Name = "Full name")]
        public string FullName { get; set; } // FullName (length: 100)

        [Column(@"Gender", Order = 5, TypeName = "nvarchar")]
        [MaxLength(10)]
        [StringLength(10)]
        [Display(Name = "Gender")]
        public string Gender { get; set; } // Gender (length: 10)

        [Column(@"DateOfBirth", Order = 6, TypeName = "date")]
        [Display(Name = "Date of birth")]
        public System.DateTime? DateOfBirth { get; set; } // DateOfBirth

        [Column(@"HomeAddress", Order = 7, TypeName = "nvarchar")]
        [MaxLength(200)]
        [StringLength(200)]
        [Display(Name = "Home address")]
        public string HomeAddress { get; set; } // HomeAddress (length: 200)

        [Column(@"StartDate", Order = 8, TypeName = "date")]
        [Display(Name = "Start date")]
        public System.DateTime? StartDate { get; set; } // StartDate

        [Column(@"PhoneNumber", Order = 9, TypeName = "nvarchar")]
        [MaxLength(20)]
        [StringLength(20)]
        [Phone]
        [Display(Name = "Phone number")]
        public string PhoneNumber { get; set; } // PhoneNumber (length: 20)

        [Column(@"IsDeleted", Order = 10, TypeName = "bit")]
        [Display(Name = "Is deleted")]
        public bool? IsDeleted { get; set; } // IsDeleted

        // Reverse navigation

        /// <summary>
        /// Child Appointments where [Appointment].[DoctorID] point to this entity (FK_dbo.Appointment_dbo.Employee_DoctorID)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Appointment> Appointments { get; set; } // Appointment.FK_dbo.Appointment_dbo.Employee_DoctorID
        /// <summary>
        /// Child Feedbacks where [Feedback].[EmployeeID] point to this entity (FK_dbo.Feedback_dbo.Employee_EmployeeID)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Feedback> Feedbacks { get; set; } // Feedback.FK_dbo.Feedback_dbo.Employee_EmployeeID

        // Foreign keys

        /// <summary>
        /// Parent Account pointed by [Employee].([AccountId]) (FK_dbo.Employee_dbo.Account_AccountID)
        /// </summary>
        [ForeignKey("AccountId")] public virtual Account Account { get; set; } // FK_dbo.Employee_dbo.Account_AccountID

        public Employee()
        {
            Appointments = new System.Collections.Generic.List<Appointment>();
            Feedbacks = new System.Collections.Generic.List<Feedback>();
        }
    }

    // Appointment
    [Table("Appointment", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public class Appointment
    {
        [Column(@"AppointmentCode", Order = 1, TypeName = "nvarchar")]
        [MaxLength(20)]
        [StringLength(20)]
        [Display(Name = "Appointment code")]
        public string AppointmentCode { get; set; } // AppointmentCode (length: 20)

        [Column(@"PatientID", Order = 2, TypeName = "int")]
        [Index(@"IX_PatientID", 1, IsUnique = false, IsClustered = false)]
        [Display(Name = "Patient ID")]
        public int? PatientId { get; set; } // PatientID

        [Column(@"DoctorID", Order = 3, TypeName = "int")]
        [Index(@"IX_DoctorID", 1, IsUnique = false, IsClustered = false)]
        [Display(Name = "Doctor ID")]
        public int? DoctorId { get; set; } // DoctorID

        [Column(@"IsEmergency", Order = 4, TypeName = "bit")]
        [Display(Name = "Is emergency")]
        public bool? IsEmergency { get; set; } // IsEmergency

        [Column(@"TestPurpose", Order = 5, TypeName = "nvarchar")]
        [MaxLength(100)]
        [StringLength(100)]
        [Display(Name = "Test purpose")]
        public string TestPurpose { get; set; } // TestPurpose (length: 100)

        [Column(@"EnterTime", Order = 6, TypeName = "datetime")]
        [Display(Name = "Enter time")]
        public System.DateTime? EnterTime { get; set; } // EnterTime

        [Column(@"ReturnTime", Order = 7, TypeName = "datetime")]
        [Display(Name = "Return time")]
        public System.DateTime? ReturnTime { get; set; } // ReturnTime

        [Column(@"Conclusion", Order = 8, TypeName = "nvarchar")]
        [MaxLength(500)]
        [StringLength(500)]
        [Display(Name = "Conclusion")]
        public string Conclusion { get; set; } // Conclusion (length: 500)

        [Column(@"ResultApproved", Order = 9, TypeName = "bit")]
        [Display(Name = "Result approved")]
        public bool? ResultApproved { get; set; } // ResultApproved

        [Column(@"Status", Order = 10, TypeName = "nvarchar")]
        [MaxLength(20)]
        [StringLength(20)]
        [Display(Name = "Status")]
        public string Status { get; set; } // Status (length: 20)

        [Column(@"IsDeleted", Order = 11, TypeName = "bit")]
        [Display(Name = "Is deleted")]
        public bool? IsDeleted { get; set; } // IsDeleted

        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"AppointmentID", Order = 12, TypeName = "int")]
        [Index(@"PK_dbo.Appointment", 1, IsUnique = true, IsClustered = true)]
        [Index(@"PK_Appointment", 1, IsUnique = true, IsClustered = false)]
        [Required]
        [Key]
        [Display(Name = "Appointment ID")]
        public int AppointmentId { get; set; } // AppointmentID (Primary key)

        [Column(@"IsPaid", Order = 13, TypeName = "bit")]
        [Display(Name = "Is paid")]
        public bool? IsPaid { get; set; } // IsPaid

        [Column(@"DoctorComment", Order = 14, TypeName = "nvarchar(max)")]
        [Display(Name = "Doctor comment")]
        public string DoctorComment { get; set; } // DoctorComment

        [Column(@"IsOnline", Order = 15, TypeName = "bit")]
        [Display(Name = "Is online")]
        public bool? IsOnline { get; set; } // IsOnline

        // Reverse navigation

        /// <summary>
        /// Child SampleGettings where [SampleGetting].[AppointmentID] point to this entity (FK_dbo.SampleGetting_dbo.Appointment_AppointmentID)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<SampleGetting> SampleGettings { get; set; } // SampleGetting.FK_dbo.SampleGetting_dbo.Appointment_AppointmentID

        // Foreign keys

        /// <summary>
        /// Parent Employee pointed by [Appointment].([DoctorId]) (FK_dbo.Appointment_dbo.Employee_DoctorID)
        /// </summary>
        [ForeignKey("DoctorId")] public virtual Employee Employee { get; set; } // FK_dbo.Appointment_dbo.Employee_DoctorID

        /// <summary>
        /// Parent Patient pointed by [Appointment].([PatientId]) (FK_dbo.Appointment_dbo.Patient_PatientID)
        /// </summary>
        [ForeignKey("PatientId")] public virtual Patient Patient { get; set; } // FK_dbo.Appointment_dbo.Patient_PatientID

        public Appointment()
        {
            SampleGettings = new System.Collections.Generic.List<SampleGetting>();
        }
    }

    // AccountToken
    [Table("AccountToken", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public class AccountToken
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"AccountTokenID", Order = 1, TypeName = "int")]
        [Index(@"PK_dbo.AccountToken", 1, IsUnique = true, IsClustered = true)]
        [Index(@"PK__AccountT__B418767CA1756B47", 1, IsUnique = true, IsClustered = false)]
        [Required]
        [Key]
        [Display(Name = "Account token ID")]
        public int AccountTokenId { get; set; } // AccountTokenID (Primary key)

        [Column(@"AccountID", Order = 2, TypeName = "int")]
        [Index(@"IX_AccountID", 1, IsUnique = false, IsClustered = false)]
        [Required]
        [Display(Name = "Account ID")]
        public int AccountId { get; set; } // AccountID

        [Column(@"TokenID", Order = 3, TypeName = "int")]
        [Index(@"IX_TokenID", 1, IsUnique = false, IsClustered = false)]
        [Required]
        [Display(Name = "Token ID")]
        public int TokenId { get; set; } // TokenID

        [Column(@"IsDeleted", Order = 4, TypeName = "bit")]
        [Display(Name = "Is deleted")]
        public bool? IsDeleted { get; set; } // IsDeleted

        // Foreign keys

        /// <summary>
        /// Parent Account pointed by [AccountToken].([AccountId]) (FK_dbo.AccountToken_dbo.Account_AccountID)
        /// </summary>
        [ForeignKey("AccountId"), Required] public virtual Account Account { get; set; } // FK_dbo.AccountToken_dbo.Account_AccountID

        /// <summary>
        /// Parent Token pointed by [AccountToken].([TokenId]) (FK_dbo.AccountToken_dbo.Token_TokenID)
        /// </summary>
        [ForeignKey("TokenId"), Required] public virtual Token Token { get; set; } // FK_dbo.AccountToken_dbo.Token_TokenID
    }

    // Account
    [Table("Account", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public class Account
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"AccountID", Order = 1, TypeName = "int")]
        [Index(@"PK_dbo.Account", 1, IsUnique = true, IsClustered = true)]
        [Index(@"PK__Account__3214EC27626EEC4A", 1, IsUnique = true, IsClustered = false)]
        [Required]
        [Key]
        [Display(Name = "Account ID")]
        public int AccountId { get; set; } // AccountID (Primary key)

        [Column(@"RoleID", Order = 2, TypeName = "int")]
        [Index(@"IX_RoleID", 1, IsUnique = false, IsClustered = false)]
        [Display(Name = "Role ID")]
        public int? RoleId { get; set; } // RoleID

        [Column(@"Email", Order = 3, TypeName = "nvarchar")]
        [MaxLength(255)]
        [StringLength(255)]
        [EmailAddress]
        [Display(Name = "Email")]
        public string Email { get; set; } // Email (length: 255)

        [Column(@"Password", Order = 4, TypeName = "nvarchar")]
        [MaxLength(128)]
        [StringLength(128)]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; } // Password (length: 128)

        [Column(@"PhoneNumber", Order = 5, TypeName = "nvarchar")]
        [MaxLength(20)]
        [StringLength(20)]
        [Phone]
        [Display(Name = "Phone number")]
        public string PhoneNumber { get; set; } // PhoneNumber (length: 20)

        [Column(@"AvatarURL", Order = 6, TypeName = "nvarchar")]
        [MaxLength(500)]
        [StringLength(500)]
        [Display(Name = "Avatar url")]
        public string AvatarUrl { get; set; } // AvatarURL (length: 500)

        [Column(@"IsDeleted", Order = 7, TypeName = "bit")]
        [Display(Name = "Is deleted")]
        public bool? IsDeleted { get; set; } // IsDeleted

        [Column(@"IdentityCardNumber", Order = 8, TypeName = "nvarchar")]
        [MaxLength(20)]
        [StringLength(20)]
        [Display(Name = "Identity card number")]
        public string IdentityCardNumber { get; set; } // IdentityCardNumber (length: 20)

        [Column(@"FullName", Order = 9, TypeName = "nvarchar")]
        [MaxLength(50)]
        [StringLength(50)]
        [Display(Name = "Full name")]
        public string FullName { get; set; } // FullName (length: 50)

        // Reverse navigation

        /// <summary>
        /// Child AccountTokens where [AccountToken].[AccountID] point to this entity (FK_dbo.AccountToken_dbo.Account_AccountID)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<AccountToken> AccountTokens { get; set; } // AccountToken.FK_dbo.AccountToken_dbo.Account_AccountID
        /// <summary>
        /// Child Employees where [Employee].[AccountID] point to this entity (FK_dbo.Employee_dbo.Account_AccountID)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Employee> Employees { get; set; } // Employee.FK_dbo.Employee_dbo.Account_AccountID
        /// <summary>
        /// Child PatientAccounts where [PatientAccount].[AccountID] point to this entity (FK_dbo.PatientAccount_dbo.Account_AccountID)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<PatientAccount> PatientAccounts { get; set; } // PatientAccount.FK_dbo.PatientAccount_dbo.Account_AccountID

        // Foreign keys

        /// <summary>
        /// Parent Role pointed by [Account].([RoleId]) (FK_dbo.Account_dbo.Role_RoleID)
        /// </summary>
        [ForeignKey("RoleId")] public virtual Role Role { get; set; } // FK_dbo.Account_dbo.Role_RoleID

        public Account()
        {
            AccountTokens = new System.Collections.Generic.List<AccountToken>();
            Employees = new System.Collections.Generic.List<Employee>();
            PatientAccounts = new System.Collections.Generic.List<PatientAccount>();
        }
    }

    #endregion

    #region POCO Configuration

    // Account
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public class AccountConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Account>
    {
        public AccountConfiguration()
            : this("dbo")
        {
        }

        public AccountConfiguration(string schema)
        {
            Property(x => x.RoleId).IsOptional();
            Property(x => x.Email).IsOptional();
            Property(x => x.Password).IsOptional();
            Property(x => x.PhoneNumber).IsOptional();
            Property(x => x.AvatarUrl).IsOptional();
            Property(x => x.IsDeleted).IsOptional();
            Property(x => x.IdentityCardNumber).IsOptional();
            Property(x => x.FullName).IsOptional();

        }
    }

    // AccountToken
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public class AccountTokenConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<AccountToken>
    {
        public AccountTokenConfiguration()
            : this("dbo")
        {
        }

        public AccountTokenConfiguration(string schema)
        {
            Property(x => x.IsDeleted).IsOptional();

        }
    }

    // Appointment
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public class AppointmentConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Appointment>
    {
        public AppointmentConfiguration()
            : this("dbo")
        {
        }

        public AppointmentConfiguration(string schema)
        {
            Property(x => x.AppointmentCode).IsOptional();
            Property(x => x.PatientId).IsOptional();
            Property(x => x.DoctorId).IsOptional();
            Property(x => x.IsEmergency).IsOptional();
            Property(x => x.TestPurpose).IsOptional();
            Property(x => x.EnterTime).IsOptional();
            Property(x => x.ReturnTime).IsOptional();
            Property(x => x.Conclusion).IsOptional();
            Property(x => x.ResultApproved).IsOptional();
            Property(x => x.Status).IsOptional();
            Property(x => x.IsDeleted).IsOptional();
            Property(x => x.IsPaid).IsOptional();
            Property(x => x.DoctorComment).IsOptional();
            Property(x => x.IsOnline).IsOptional();

        }
    }

    // Employee
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public class EmployeeConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Employee>
    {
        public EmployeeConfiguration()
            : this("dbo")
        {
        }

        public EmployeeConfiguration(string schema)
        {
            Property(x => x.AccountId).IsOptional();
            Property(x => x.Status).IsOptional();
            Property(x => x.FullName).IsOptional();
            Property(x => x.Gender).IsOptional();
            Property(x => x.DateOfBirth).IsOptional();
            Property(x => x.HomeAddress).IsOptional();
            Property(x => x.StartDate).IsOptional();
            Property(x => x.PhoneNumber).IsOptional();
            Property(x => x.IsDeleted).IsOptional();

        }
    }

    // ExportPaper
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public class ExportPaperConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<ExportPaper>
    {
        public ExportPaperConfiguration()
            : this("dbo")
        {
        }

        public ExportPaperConfiguration(string schema)
        {
            Property(x => x.ExportPaperCode).IsOptional();
            Property(x => x.CreateDate).IsOptional();
            Property(x => x.AccountId).IsOptional();
            Property(x => x.Note).IsOptional();
            Property(x => x.Status).IsOptional();
            Property(x => x.IsDeleted).IsOptional();
        }
    }

    // ExportPaperDetail
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public class ExportPaperDetailConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<ExportPaperDetail>
    {
        public ExportPaperDetailConfiguration()
            : this("dbo")
        {
        }

        public ExportPaperDetailConfiguration(string schema)
        {
            Property(x => x.ExportPaperId).IsOptional();
            Property(x => x.SuppliesId).IsOptional();
            Property(x => x.Unit).IsOptional();
            Property(x => x.Quantity).IsOptional();
            Property(x => x.Note).IsOptional();
            Property(x => x.IsDeleted).IsOptional();

        }
    }

    // Feedback
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public class FeedbackConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Feedback>
    {
        public FeedbackConfiguration()
            : this("dbo")
        {
        }

        public FeedbackConfiguration(string schema)
        {
            Property(x => x.PatientId).IsOptional();
            Property(x => x.EmployeeId).IsOptional();
            Property(x => x.Content).IsOptional();
            Property(x => x.ReceivedDateTime).IsOptional();
            Property(x => x.IsDeleted).IsOptional();
            Property(x => x.Status).IsOptional();
            Property(x => x.StarRating).IsOptional();

        }
    }

    // HospitalSuggestion
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public class HospitalSuggestionConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<HospitalSuggestion>
    {
        public HospitalSuggestionConfiguration()
            : this("dbo")
        {
        }

        public HospitalSuggestionConfiguration(string schema)
        {
            Property(x => x.DiseaseName).IsOptional();
            Property(x => x.HospitalList).IsOptional();
            Property(x => x.HospitalAdd).IsOptional();
            Property(x => x.HospitalPhone).IsOptional();
            Property(x => x.IsDeleted).IsOptional();
        }
    }

    // ImportPaper
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public class ImportPaperConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<ImportPaper>
    {
        public ImportPaperConfiguration()
            : this("dbo")
        {
        }

        public ImportPaperConfiguration(string schema)
        {
            Property(x => x.ImportPaperCode).IsOptional();
            Property(x => x.CreateDate).IsOptional();
            Property(x => x.AccountId).IsOptional();
            Property(x => x.Note).IsOptional();
            Property(x => x.IsDeleted).IsOptional();
        }
    }

    // ImportPaperDetail
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public class ImportPaperDetailConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<ImportPaperDetail>
    {
        public ImportPaperDetailConfiguration()
            : this("dbo")
        {
        }

        public ImportPaperDetailConfiguration(string schema)
        {
            Property(x => x.ImportPaperId).IsOptional();
            Property(x => x.SuppliesId).IsOptional();
            Property(x => x.Unit).IsOptional();
            Property(x => x.Quantity).IsOptional();
            Property(x => x.Note).IsOptional();
            Property(x => x.IsDeleted).IsOptional();

        }
    }

    // LabTest
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public class LabTestConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<LabTest>
    {
        public LabTestConfiguration()
            : this("dbo")
        {
        }

        public LabTestConfiguration(string schema)
        {
            Property(x => x.LabTestCode).IsOptional();
            Property(x => x.LabTestName).IsOptional();
            Property(x => x.Description).IsOptional();
            Property(x => x.Price).IsOptional();
            Property(x => x.IsDeleted).IsOptional();
            Property(x => x.SampleId).IsOptional();

        }
    }

    // LabTesting
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public class LabTestingConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<LabTesting>
    {
        public LabTestingConfiguration()
            : this("dbo")
        {
        }

        public LabTestingConfiguration(string schema)
        {
            Property(x => x.LabTestId).IsOptional();
            Property(x => x.SampleGettingId).IsOptional();
            Property(x => x.Status).IsOptional();
            Property(x => x.IsDeleted).IsOptional();
            Property(x => x.MachineSlot).IsOptional();

        }
    }

    // LabTestingIndex
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public class LabTestingIndexConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<LabTestingIndex>
    {
        public LabTestingIndexConfiguration()
            : this("dbo")
        {
        }

        public LabTestingIndexConfiguration(string schema)
        {
            Property(x => x.LabTestingId).IsOptional();
            Property(x => x.IndexName).IsOptional();
            Property(x => x.IndexValue).IsOptional();
            Property(x => x.LowNormalHigh).IsOptional();
            Property(x => x.NormalRange).IsOptional();
            Property(x => x.Unit).IsOptional();
            Property(x => x.IsDeleted).IsOptional();

        }
    }

    // Patient
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public class PatientConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Patient>
    {
        public PatientConfiguration()
            : this("dbo")
        {
        }

        public PatientConfiguration(string schema)
        {
            Property(x => x.PatientCode).IsOptional();
            Property(x => x.AccountId).IsOptional();
            Property(x => x.FullName).IsOptional();
            Property(x => x.Gender).IsOptional();
            Property(x => x.DateOfBirth).IsOptional();
            Property(x => x.PhoneNumber).IsOptional();
            Property(x => x.HomeAddress).IsOptional();
            Property(x => x.CompanyAddress).IsOptional();
            Property(x => x.IsDeleted).IsOptional();
            Property(x => x.IsOnline).IsOptional();
            Property(x => x.IdentityCardNumber).IsOptional();
        }
    }

    // PatientAccount
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public class PatientAccountConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<PatientAccount>
    {
        public PatientAccountConfiguration()
            : this("dbo")
        {
        }

        public PatientAccountConfiguration(string schema)
        {
            Property(x => x.IsDeleted).IsOptional();

        }
    }

    // Role
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public class RoleConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Role>
    {
        public RoleConfiguration()
            : this("dbo")
        {
        }

        public RoleConfiguration(string schema)
        {
            Property(x => x.RoleName).IsOptional();
        }
    }

    // Sample
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public class SampleConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Sample>
    {
        public SampleConfiguration()
            : this("dbo")
        {
        }

        public SampleConfiguration(string schema)
        {
            Property(x => x.SampleGroupId).IsOptional();
            Property(x => x.SampleName).IsOptional();
            Property(x => x.Description).IsOptional();
            Property(x => x.IsDeleted).IsOptional();

        }
    }

    // SampleGetting
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public class SampleGettingConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<SampleGetting>
    {
        public SampleGettingConfiguration()
            : this("dbo")
        {
        }

        public SampleGettingConfiguration(string schema)
        {
            Property(x => x.AppointmentId).IsOptional();
            Property(x => x.SampleId).IsOptional();
            Property(x => x.Status).IsOptional();
            Property(x => x.IsDeleted).IsOptional();
            Property(x => x.SampleGettingCode).IsOptional();
            Property(x => x.IsPaid).IsOptional();
            Property(x => x.TableId).IsOptional();
            Property(x => x.SlotId).IsOptional();
            Property(x => x.GettingDate).IsOptional();
            Property(x => x.OrderNumber).IsOptional();
            Property(x => x.IsGot).IsOptional();

        }
    }

    // SampleGroup
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public class SampleGroupConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<SampleGroup>
    {
        public SampleGroupConfiguration()
            : this("dbo")
        {
        }

        public SampleGroupConfiguration(string schema)
        {
            Property(x => x.GroupName).IsOptional();
            Property(x => x.GettingDuration).IsOptional();
            Property(x => x.OpenTime).IsOptional();
            Property(x => x.CloseTime).IsOptional();
            Property(x => x.IsDeleted).IsOptional();
        }
    }

    // Slot
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public class SlotConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Slot>
    {
        public SlotConfiguration()
            : this("dbo")
        {
        }

        public SlotConfiguration(string schema)
        {
            Property(x => x.StartTime).IsOptional();
            Property(x => x.FinishTime).IsOptional();
            Property(x => x.SlotName).IsOptional();
            Property(x => x.SampleGroupId).IsOptional();
            Property(x => x.IsDeleted).IsOptional();

        }
    }

    // Supply
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public class SupplyConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Supply>
    {
        public SupplyConfiguration()
            : this("dbo")
        {
        }

        public SupplyConfiguration(string schema)
        {
            Property(x => x.SuppliesCode).IsOptional();
            Property(x => x.SuppliesName).IsOptional();
            Property(x => x.SuppliesTypeId).IsOptional();
            Property(x => x.Quantity).IsOptional();
            Property(x => x.Unit).IsOptional();
            Property(x => x.Note).IsOptional();
            Property(x => x.IsDeleted).IsOptional();

        }
    }

    // SupplyType
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public class SupplyTypeConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<SupplyType>
    {
        public SupplyTypeConfiguration()
            : this("dbo")
        {
        }

        public SupplyTypeConfiguration(string schema)
        {
            Property(x => x.SuppliesTypeName).IsOptional();
            Property(x => x.IsDeleted).IsOptional();
        }
    }

    // Table
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public class TableConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Table>
    {
        public TableConfiguration()
            : this("dbo")
        {
        }

        public TableConfiguration(string schema)
        {
            Property(x => x.SampleGroupId).IsOptional();
            Property(x => x.TableName).IsOptional().IsFixedLength();
            Property(x => x.IsDeleted).IsOptional();

        }
    }

    // Token
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.36.1.0")]
    public class TokenConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Token>
    {
        public TokenConfiguration()
            : this("dbo")
        {
        }

        public TokenConfiguration(string schema)
        {
            Property(x => x.TokenString).IsOptional();
            Property(x => x.IsDeleted).IsOptional();
        }
    }

    #endregion

}
// </auto-generated>

